# Generated by Django 4.0.3 on 2022-05-26 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('debah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deba7',
            name='org',
            field=models.ForeignKey(limit_choices_to={'is_org': True}, on_delete=django.db.models.deletion.CASCADE, related_name='org', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deba7',
            name='taken',
            field=models.IntegerField(default=0),
        ),
    ]
