# Generated by Django 4.0.3 on 2022-05-27 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debah', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='date_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('debah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debah', to='debah.deba7')),
                ('organisation', models.ForeignKey(limit_choices_to={'is_org': True}, on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to=settings.AUTH_USER_MODEL)),
                ('simple_user', models.ForeignKey(limit_choices_to={'is_org': False}, on_delete=django.db.models.deletion.CASCADE, related_name='simple_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
