# Generated by Django 4.0.3 on 2022-05-27 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_date_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request_s',
            old_name='baladiya',
            new_name='Address',
        ),
        migrations.AddField(
            model_name='date_request',
            name='jour',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='date_request',
            name='date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
